"""
services/enrichment/mood_anchor_matcher.py
==========================================

MoodAnchorMatcher — refines a raw SigLIP visual embedding into one of 10
fine-grained mood classes using cosine similarity against pre-computed
text anchors, with an optional Gemma ai_mood prior blend.

Design contract (Design §5.2 Step 2):
- cosine distance against anchors as base score.
- prior_mood (4-class Gemma output) adds an additive boost to a subset of
  the 10 anchor classes before softmax, weighted by prior_weight.
- confidence = softmax-max over the (possibly prior-adjusted) cosine scores.

Gemma 4-class → 10-class prior mapping
---------------------------------------
  energetic → boost {euphoric, aggressive, uplifting}
  calm      → boost {calm, ambient, dreamy}
  dramatic  → boost {dark, tense, aggressive}
  ambient   → boost {ambient, dreamy, calm}
  (unknown) → no boost

Prior blend algorithm
---------------------
  scores[i] += prior_weight * 1.0   for each boosted anchor i
  confidence = max(softmax(scores))
  result     = argmax(softmax(scores))
"""

from __future__ import annotations

from pathlib import Path

import numpy as np

# ---------------------------------------------------------------------------
# Prior mapping: Gemma 4-class → subset of 10 mood anchor classes to boost
# ---------------------------------------------------------------------------
_PRIOR_BOOST_MAP: dict[str, set[str]] = {
    "energetic": {"euphoric", "aggressive", "uplifting"},
    "calm": {"calm", "ambient", "dreamy"},
    "dramatic": {"dark", "tense", "aggressive"},
    "ambient": {"ambient", "dreamy", "calm"},
}


def _softmax(x: np.ndarray) -> np.ndarray:
    """Numerically stable row-wise softmax. Accepts 1-D or 2-D arrays."""
    e: np.ndarray = np.exp(x - np.max(x, axis=-1, keepdims=True))
    result: np.ndarray = e / e.sum(axis=-1, keepdims=True)
    return result


class MoodAnchorMatcher:
    """Refine a SigLIP visual embedding to one of 10 mood classes.

    Parameters
    ----------
    anchors_path:
        Path to the ``.npz`` file generated by ``scripts/generate_mood_anchors.py``.
        Arrays are sorted alphabetically so the ordering is deterministic across
        platforms regardless of the order they were saved in.
    temperature:
        Softmax temperature applied to cosine scores before computing
        probabilities.  Lower values make the distribution peakier (more
        decisive).  Default ``0.1`` matches typical CLIP/SigLIP logit-scale
        usage (logit_scale ≈ 10), ensuring that an exact-anchor embedding
        produces confidence > 0.9.
    """

    def __init__(
        self,
        anchors_path: str | Path = "config/mood_anchors.npz",
        temperature: float = 0.1,
    ) -> None:
        self._temperature = temperature
        data = np.load(str(anchors_path))
        # Alphabetical sort → deterministic ordering on all platforms.
        self._names: list[str] = sorted(data.files)
        self._anchors: np.ndarray = np.stack(
            [data[n] for n in self._names], axis=0
        ).astype(
            np.float32
        )  # shape (10, D)

        # Pre-normalize once for speed.
        norms = np.linalg.norm(self._anchors, axis=1, keepdims=True)
        self._anchors_normalized: np.ndarray = self._anchors / norms  # (10, D)

    # ------------------------------------------------------------------
    # Public API
    # ------------------------------------------------------------------

    def refine(
        self,
        embedding: np.ndarray,
        prior_mood: str | None = None,
        prior_weight: float = 0.6,
    ) -> tuple[str, float]:
        """Return ``(mood_name, confidence)`` for a single visual embedding.

        Parameters
        ----------
        embedding:
            1-D float array of shape ``(D,)`` — a SigLIP visual embedding
            (typically 1152-d).
        prior_mood:
            Optional Gemma ai_mood class string.  Must be one of
            ``"energetic" | "calm" | "dramatic" | "ambient"`` or ``None``.
            Unknown strings are treated as ``None`` (no boost applied).
        prior_weight:
            How strongly the prior biases the result.  ``0.0`` → no prior
            effect; large values → prior dominates.  Default ``0.6``.
        """
        emb = embedding.astype(np.float32)
        norm = float(np.linalg.norm(emb))
        if norm == 0.0:
            raise ValueError("embedding has zero L2 norm — cannot normalize")
        e_hat: np.ndarray = emb / norm  # (D,)

        # Cosine similarity: (10,)
        scores: np.ndarray = self._anchors_normalized @ e_hat

        # Prior blend — additive boost before softmax.
        if prior_mood is not None:
            boost_set = _PRIOR_BOOST_MAP.get(prior_mood, set())
            for i, name in enumerate(self._names):
                if name in boost_set:
                    scores[i] += prior_weight * 1.0

        probs = _softmax(scores / self._temperature)
        idx = int(np.argmax(probs))
        return self._names[idx], float(probs[idx])

    def refine_batch(
        self,
        embeddings: np.ndarray,
        prior_moods: list[str | None] | None = None,
        prior_weight: float = 0.6,
    ) -> list[tuple[str, float]]:
        """Vectorised batch version of :meth:`refine`.

        Parameters
        ----------
        embeddings:
            2-D array of shape ``(N, D)``.
        prior_moods:
            List of length ``N`` with optional prior class strings (``None``
            entries are skipped).  Pass ``None`` to disable prior for all rows.
        prior_weight:
            Shared prior weight for all rows.
        """
        embs = embeddings.astype(np.float32)  # (N, D)
        norms = np.linalg.norm(embs, axis=1, keepdims=True)  # (N, 1)
        if np.any(norms == 0.0):
            raise ValueError("One or more embeddings have zero L2 norm")
        e_hat = embs / norms  # (N, D)

        # Cosine: (N, 10)
        scores: np.ndarray = e_hat @ self._anchors_normalized.T

        # Prior blend per row.
        if prior_moods is not None:
            for row, pm in enumerate(prior_moods):
                if pm is None:
                    continue
                boost_set = _PRIOR_BOOST_MAP.get(pm, set())
                for col, name in enumerate(self._names):
                    if name in boost_set:
                        scores[row, col] += prior_weight * 1.0

        probs = _softmax(scores / self._temperature)  # (N, 10)
        idxs = np.argmax(probs, axis=1)  # (N,)
        return [
            (self._names[int(idx)], float(probs[i, int(idx)]))
            for i, idx in enumerate(idxs)
        ]

    # ------------------------------------------------------------------
    # Internal helpers (used in tests)
    # ------------------------------------------------------------------

    def _get_anchor(self, name: str) -> np.ndarray:
        """Return the stored (unnormalized) anchor vector for *name*.

        Used in unit tests to produce synthetic embeddings that are
        guaranteed to be nearest to a particular anchor.
        """
        idx = self._names.index(name)
        result: np.ndarray = self._anchors[idx].copy()
        return result
