"""Add soft delete support columns

Revision ID: fec604708ce8
Revises: d6g8h9i0j1k2
Create Date: 2026-04-08 23:40:30.919834
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fec604708ce8'
down_revision: Union[str, None] = 'd6g8h9i0j1k2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('agent_feedback', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_feedback_action'))
        batch_op.drop_index(batch_op.f('ix_agent_feedback_rating'))

    with op.batch_alter_table('ai_pacing_memory', schema=None) as batch_op:
        batch_op.alter_column('siglip_tags',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_ai_pacing_memory_audio_track_id'))
        batch_op.create_foreign_key(None, 'audio_tracks', ['audio_track_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'scenes', ['scene_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('audio_tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.alter_column('energy_curve',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('mood',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('genre',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('spectral_bands',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('key_modulation_data',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('harmonic_tension_curve',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_audio_tracks_project_id'))
        batch_op.drop_index(batch_op.f('uq_audio_tracks_project_file'))
        batch_op.create_unique_constraint('uq_audio_tracks_project_file', ['project_id', 'file_path'])

    with op.batch_alter_table('audio_video_anchors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audio_video_anchors_audio_track_id'))
        batch_op.drop_index(batch_op.f('ix_audio_video_anchors_video_clip_id'))

    with op.batch_alter_table('beatgrids', schema=None) as batch_op:
        batch_op.alter_column('beat_positions',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('downbeat_positions',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('energy_per_beat',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('stem_weighted_energy',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('onset_kick_data',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('onset_snare_data',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('onset_hihat_data',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('groove_template',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_beatgrids_audio_track_id'))
        batch_op.drop_index(batch_op.f('uq_beatgrids_audio_track_id'))
        batch_op.create_unique_constraint(None, ['audio_track_id'])

    with op.batch_alter_table('clip_anchors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clip_anchors_timeline_entry_id'))

    with op.batch_alter_table('hotcues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hotcues_audio_track_id'))

    with op.batch_alter_table('model_registry', schema=None) as batch_op:
        batch_op.alter_column('metadata_json',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_model_registry_last_used'))
        batch_op.drop_index(batch_op.f('ix_model_registry_source'))

    with op.batch_alter_table('pacing_blueprints', schema=None) as batch_op:
        batch_op.alter_column('energy_curve',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.alter_column('ai_caption',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('ai_mood',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('ai_tags',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.drop_index(batch_op.f('ix_scenes_video_clip_id'))

    with op.batch_alter_table('structure_segments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_structure_segments_audio_track_id'))

    with op.batch_alter_table('timeline_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_timeline_entries_project_id'))

    with op.batch_alter_table('video_clips', schema=None) as batch_op:
        batch_op.add_column(sa.Column('playback_offset', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_video_clips_project_id'))
        batch_op.drop_index(batch_op.f('uq_video_clips_project_file'))
        batch_op.create_unique_constraint('uq_video_clips_project_file', ['project_id', 'file_path'])

    with op.batch_alter_table('waveform_data', schema=None) as batch_op:
        batch_op.alter_column('band_low',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=False)
        batch_op.alter_column('band_mid',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=False)
        batch_op.alter_column('band_high',
               existing_type=sa.TEXT(),
               type_=sa.JSON(),
               existing_nullable=False)
        batch_op.drop_index(batch_op.f('ix_waveform_data_audio_track_id'))
        batch_op.drop_index(batch_op.f('uq_waveform_data_audio_track_id'))
        batch_op.create_unique_constraint(None, ['audio_track_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('waveform_data', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('uq_waveform_data_audio_track_id'), ['audio_track_id'], unique=1)
        batch_op.create_index(batch_op.f('ix_waveform_data_audio_track_id'), ['audio_track_id'], unique=False)
        batch_op.alter_column('band_high',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('band_mid',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('band_low',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=False)

    with op.batch_alter_table('video_clips', schema=None) as batch_op:
        batch_op.drop_constraint('uq_video_clips_project_file', type_='unique')
        batch_op.create_index(batch_op.f('uq_video_clips_project_file'), ['project_id', 'file_path'], unique=1)
        batch_op.create_index(batch_op.f('ix_video_clips_project_id'), ['project_id'], unique=False)
        batch_op.drop_column('deleted_at')
        batch_op.drop_column('playback_offset')

    with op.batch_alter_table('timeline_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_timeline_entries_project_id'), ['project_id'], unique=False)

    with op.batch_alter_table('structure_segments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_structure_segments_audio_track_id'), ['audio_track_id'], unique=False)

    with op.batch_alter_table('scenes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scenes_video_clip_id'), ['video_clip_id'], unique=False)
        batch_op.alter_column('ai_tags',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('ai_mood',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('ai_caption',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('pacing_blueprints', schema=None) as batch_op:
        batch_op.alter_column('energy_curve',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('model_registry', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_registry_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_registry_last_used'), ['last_used_at'], unique=False)
        batch_op.alter_column('metadata_json',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('hotcues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hotcues_audio_track_id'), ['audio_track_id'], unique=False)

    with op.batch_alter_table('clip_anchors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_clip_anchors_timeline_entry_id'), ['timeline_entry_id'], unique=False)

    with op.batch_alter_table('beatgrids', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_index(batch_op.f('uq_beatgrids_audio_track_id'), ['audio_track_id'], unique=1)
        batch_op.create_index(batch_op.f('ix_beatgrids_audio_track_id'), ['audio_track_id'], unique=False)
        batch_op.alter_column('groove_template',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('onset_hihat_data',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('onset_snare_data',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('onset_kick_data',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('stem_weighted_energy',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('energy_per_beat',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('downbeat_positions',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('beat_positions',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('audio_video_anchors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audio_video_anchors_video_clip_id'), ['video_clip_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audio_video_anchors_audio_track_id'), ['audio_track_id'], unique=False)

    with op.batch_alter_table('audio_tracks', schema=None) as batch_op:
        batch_op.drop_constraint('uq_audio_tracks_project_file', type_='unique')
        batch_op.create_index(batch_op.f('uq_audio_tracks_project_file'), ['project_id', 'file_path'], unique=1)
        batch_op.create_index(batch_op.f('ix_audio_tracks_project_id'), ['project_id'], unique=False)
        batch_op.alter_column('harmonic_tension_curve',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('key_modulation_data',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('spectral_bands',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('genre',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('mood',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('energy_curve',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('deleted_at')

    with op.batch_alter_table('ai_pacing_memory', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_index(batch_op.f('ix_ai_pacing_memory_audio_track_id'), ['audio_track_id'], unique=False)
        batch_op.alter_column('siglip_tags',
               existing_type=sa.JSON(),
               type_=sa.TEXT(),
               existing_nullable=True)

    with op.batch_alter_table('agent_feedback', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agent_feedback_rating'), ['rating'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_feedback_action'), ['action_name'], unique=False)

    # ### end Alembic commands ###
